### ISSUE TITLE
[XOSC] Implement Check for Rule 35 "xml.valid_xml_document"

### ISSUE THREAD

**Issue by heuerfin** [asam-ev/qc-openscenarioxml#39]
### Link rule in excel

[Link rule in excel](https://asamev.sharepoint.com/:x:/r/sites/openscenario/P_2024_02/Rules.xlsx?d=wc1a43e9cf42a45019c22676baa7f5fef&csf=1&web=1&e=ZtlXdK&nav=MTJfSDEwX3swMDAwMDAwMC0wMDAxLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDB9)
Rule excel ref ID: "35"
Rule name: "valid_xml_document"
Rule group: "xml"
Severity: ERROR
Complexity: Not defined
Rule ID: qc-openscenario:xosc:1.3.1:xml.valid_xml_document

### Link to standard

[1 Scope](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/01_scope/01_scope.html)

### Rule text

The given file to check must be a valid XML document. (ASAM OpenSCENARIO specifies the modeling approach how to describe dynamic content in driving application simulations using the Extensible Markup Language (XML)).

### Additional context

None

**Comment by romanodanilo** [comment]
This issue is a copy of https://github.com/asam-ev/qc-openscenarioxml/issues/1
which has been alredy implemented with PR #1
